import type {
  EcoFunction,
  Kind,
  Layer,
  Nutrients,
  PlantColor,
  RootDepth,
  Silhouette,
  Soil,
  Species,
  SunNeed,
  WaterNeed,
} from "./types";

type Draft = {
  id: string;
  name: string;
  latin: string;
  family: string;
  kind?: Kind;
  layer: Layer;
  edible?: boolean;
  functions: EcoFunction[];
  hz: [number, number];
  soils?: Soil[];
  water?: WaterNeed;
  sun?: SunNeed;
  root?: RootDepth;
  years?: number;
  companions?: string[];
  antagonists?: string[];
  allelopathic?: boolean;
  livestockSafe?: boolean;
  fodderFor?: string[];
  nutrients?: Nutrients;
  description: string;
  agro: string;
  yields: string;
  color: PlantColor;
  silhouette: Silhouette;
};

function s(d: Draft): Species {
  return {
    id: d.id,
    name: d.name,
    latin: d.latin,
    family: d.family,
    kind: d.kind ?? "plant",
    layer: d.layer,
    edible: d.edible ?? true,
    functions: d.functions,
    hardinessMin: d.hz[0],
    hardinessMax: d.hz[1],
    soils: d.soils ?? ["sand", "loam"],
    water: d.water ?? "moderate",
    sun: d.sun ?? "full",
    root: d.root ?? "medium",
    yearsToYield: d.years ?? 3,
    companions: d.companions ?? [],
    antagonists: d.antagonists ?? [],
    allelopathic: d.allelopathic ?? false,
    livestockSafe: d.livestockSafe ?? true,
    fodderFor: d.fodderFor ?? [],
    nutrients: d.nutrients ?? {},
    description: d.description,
    agro: d.agro,
    yields: d.yields,
    color: d.color,
    silhouette: d.silhouette,
  };
}

/** Zone 9b flatwoods species that the temperate catalog never carried. */
export const FLORIDA_SPECIES: Species[] = [
  s({
    id: "avocado",
    name: "Cold-hardy avocado",
    latin: "Persea americana",
    family: "Lauraceae",
    layer: "canopy",
    functions: ["food"],
    hz: [8, 11],
    soils: ["sand", "loam", "silt"],
    water: "moderate",
    root: "medium",
    years: 4,
    companions: ["citrus", "pigeon-pea", "lemongrass", "perennial-peanut"],
    livestockSafe: false,
    nutrients: { vitaminE: 40, fiber: 35, potassium: 45, oleic: 70 },
    description: "West-Indian and Mexican types that take a Pasco frost if they are established. ‘Brogdon’, ‘Fantastic’, ‘Joey’ — not a supermarket Hass.",
    agro: "Mound or berm only. High water table is the killer, not the thermometer. Mulch thick, never bury the graft. Wind from June storms splits limbs — stake the first years.",
    yields: "Fruit, shade, oil-rich flesh",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "mango",
    name: "Mango",
    latin: "Mangifera indica",
    family: "Anacardiaceae",
    layer: "canopy",
    functions: ["food"],
    hz: [9, 11],
    water: "moderate",
    years: 5,
    companions: ["citrus", "pineapple", "pigeon-pea"],
    livestockSafe: false,
    nutrients: { vitaminA: 50, vitaminC: 55, fiber: 30, carotenoids: 45 },
    description: "Selected cultivars for 9b (‘Glenn’, ‘Carrie’, ‘Ice Cream’) that fruit after a rare frost if wood is mature.",
    agro: "Only on a raised pad. One ponded June will take a young tree. Plant at the start of the rains. Keep grass off the trunk.",
    yields: "Fruit",
    color: "coral",
    silhouette: "canopy",
  }),
  s({
    id: "longan",
    name: "Longan",
    latin: "Dimocarpus longan",
    family: "Sapindaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [9, 11],
    water: "moderate",
    years: 5,
    companions: ["lychee", "citrus"],
    nutrients: { vitaminC: 40, potassium: 30, copper: 25 },
    description: "A soapberry cousin of lychee. Wants heat, even moisture, and protection from the one hard freeze.",
    agro: "Mound. A frost cloth the first three winters is cheaper than a replacement. Fruit is on last year's wood — prune with that in mind.",
    yields: "Fruit",
    color: "sage",
    silhouette: "fruit",
  }),
  s({
    id: "lychee",
    name: "Lychee",
    latin: "Litchi chinensis",
    family: "Sapindaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [9, 11],
    water: "moderate",
    years: 6,
    companions: ["longan"],
    nutrients: { vitaminC: 60, copper: 30, polyphenols: 35 },
    description: "Needs a mild winter chill to flower and hates wet feet. Marginal in Zephyrhills — treat as a protected experiment.",
    agro: "South wall or mound, never a slough. If it does not flower after three warm winters, it is the climate, not you.",
    yields: "Fruit (irregular)",
    color: "rose",
    silhouette: "fruit",
  }),
  s({
    id: "citrus",
    name: "Citrus (improved stock)",
    latin: "Citrus × sinensis",
    family: "Rutaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [9, 11],
    soils: ["sand", "loam"],
    water: "moderate",
    years: 3,
    companions: ["guava", "pigeon-pea", "lemongrass", "perennial-peanut"],
    antagonists: ["oak-white"],
    nutrients: { vitaminC: 90, fiber: 30, folate: 25, flavonoids: 40 },
    description: "Sweet orange, tangerine, and lemon on phytophthora-aware rootstocks. The Florida crop, if the water is managed.",
    agro: "Mound or berm. Greening is real — buy clean trees, watch psyllids, do not pretend the acre is 1998. Lemongrass at the drip is a useful edge.",
    yields: "Fruit, blossom, oil",
    color: "mustard",
    silhouette: "fruit",
  }),
  s({
    id: "guava",
    name: "Guava",
    latin: "Psidium guajava",
    family: "Myrtaceae",
    layer: "subcanopy",
    functions: ["food", "medicine"],
    hz: [9, 11],
    water: "moderate",
    years: 2,
    companions: ["citrus", "banana", "pigeon-pea"],
    nutrients: { vitaminC: 95, fiber: 40, lycopene: 50, potassium: 30 },
    description: "Fast, fragrant, and generous. Fruit fly is the tax. Pink and white flesh both belong here.",
    agro: "More forgiving of sand than avocado. Still hates standing water. Bag fruit or accept wormy harvests in late summer.",
    yields: "Fruit, leaves",
    color: "sage",
    silhouette: "fruit",
  }),
  s({
    id: "feijoa",
    name: "Feijoa / pineapple guava",
    latin: "Acca sellowiana",
    family: "Myrtaceae",
    layer: "subcanopy",
    functions: ["food", "windbreak"],
    hz: [8, 10],
    water: "moderate",
    years: 3,
    companions: ["citrus", "loquat"],
    nutrients: { vitaminC: 45, fiber: 35, folate: 20 },
    description: "A cooler myrtle. Handles a Pasco frost better than mango. Fruit drops when ripe — plant where you will hear it.",
    agro: "Mound on wet sites. Two cultivars for pollination. A hedge that also pays.",
    yields: "Fruit, hedge",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "loquat",
    name: "Loquat",
    latin: "Eriobotrya japonica",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [8, 11],
    years: 3,
    companions: ["fig", "citrus"],
    nutrients: { vitaminA: 40, potassium: 30, fiber: 25 },
    description: "Winter flowers, spring fruit. One of the few rosaceous trees that actually belongs in 9b.",
    agro: "Tolerates sand and some wet better than apple ever will. Fireblight is possible; do not baby it with high nitrogen.",
    yields: "Fruit",
    color: "mustard",
    silhouette: "fruit",
  }),
  s({
    id: "pigeon-pea",
    name: "Pigeon pea",
    latin: "Cajanus cajan",
    family: "Fabaceae",
    layer: "shrub",
    functions: ["nitrogen-fixer", "food", "nurse", "fodder", "mulch"],
    hz: [9, 11],
    soils: ["sand", "loam", "rocky", "clay"],
    water: "moderate",
    years: 0,
    companions: ["avocado", "citrus", "mango", "perennial-peanut"],
    fodderFor: ["goat", "chicken", "sheep"],
    nutrients: { protein: 55, fiber: 50, folate: 45, lysine: 50, essentialAA: 40 },
    description: "The tropical nurse. A short-lived woody legume that shades a mound, drops mulch, and feeds you while the avocado is still a stick.",
    agro: "Sow with the rains. Coppice in year 2–3 onto the drip line. Let it die after it has done the job. This is the pigeon pea that clover cannot be in a Florida summer.",
    yields: "Peas, mulch, N, shade",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "inga",
    name: "Ice-cream bean / Inga",
    latin: "Inga edulis",
    family: "Fabaceae",
    layer: "canopy",
    functions: ["nitrogen-fixer", "food", "nurse", "mulch"],
    hz: [10, 11],
    water: "wet",
    years: 3,
    companions: ["cacao", "banana", "citrus"],
    nutrients: { fiber: 20, vitaminC: 15 },
    description: "A wet-foot N-fixer with a sweet pulp. Marginal in 9b — a frost will knock it; a warm pocket will keep it.",
    agro: "Use as a nurse only if you have a protected, wetter pad. Not a Pasco default. Sesbania and pigeon pea are the safer fixers.",
    yields: "Pulp, N, shade",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "sesbania",
    name: "Sesbania",
    latin: "Sesbania sesban",
    family: "Fabaceae",
    layer: "shrub",
    functions: ["nitrogen-fixer", "nurse", "fodder", "mulch"],
    hz: [8, 11],
    soils: ["sand", "loam", "clay", "silt"],
    water: "wet",
    years: 0,
    companions: ["mulberry", "elderberry", "duck"],
    fodderFor: ["goat", "sheep"],
    nutrients: { protein: 35 },
    description: "A wet-soil nitrogen fixer. Fast, pithy, and honest about a high water table.",
    agro: "The fixer you plant in the slough where pigeon pea sulks. Coppice. Do not let it seed into a wetland you do not own.",
    yields: "Mulch, N, browse",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "perennial-peanut",
    name: "Perennial peanut",
    latin: "Arachis glabrata",
    family: "Fabaceae",
    layer: "groundcover",
    functions: ["nitrogen-fixer", "forage", "mulch"],
    hz: [8, 11],
    soils: ["sand", "loam"],
    water: "moderate",
    sun: "full",
    years: 1,
    companions: ["citrus", "avocado", "pecan", "pine"],
    fodderFor: ["chicken", "sheep", "goat"],
    nutrients: { protein: 30, fiber: 20 },
    description: "Rhizoma perennial peanut. The living mulch that actually survives a Florida summer, unlike white clover.",
    agro: "Plant sprigs, not seed. Year one looks thin. Year two closes sand. Mow or graze lightly. This is the floor of a 9b grove.",
    yields: "Forage, N, living mulch",
    color: "sage",
    silhouette: "ground",
  }),
  s({
    id: "cassava",
    name: "Cassava",
    latin: "Manihot esculenta",
    family: "Euphorbiaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [9, 11],
    soils: ["sand", "loam"],
    water: "moderate",
    years: 0,
    livestockSafe: false,
    nutrients: { resistantStarch: 60, vitaminC: 25 },
    description: "A calorie shrub. Bitter types must be processed. Sweet types still want a known source.",
    agro: "Loves sand and heat. Hates freeze and wet feet. A good alley crop while trees are young. Livestock should not free-feed the leaves.",
    yields: "Roots, leaves (processed)",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "pineapple",
    name: "Pineapple",
    latin: "Ananas comosus",
    family: "Bromeliaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [9, 11],
    soils: ["sand"],
    water: "moderate",
    years: 2,
    companions: ["mango", "citrus"],
    nutrients: { vitaminC: 70, manganese: 50, fiber: 25 },
    description: "A bromeliad that fruits once, then pups. Wants heat, drainage, and patience.",
    agro: "Mound or bed. A frost cloth over a patch is cheaper than buying fruit. Do not plant in a swale.",
    yields: "Fruit, pups",
    color: "mustard",
    silhouette: "tuft",
  }),
  s({
    id: "passionfruit",
    name: "Passionfruit",
    latin: "Passiflora edulis",
    family: "Passifloraceae",
    layer: "vine",
    functions: ["food", "pollinator"],
    hz: [9, 11],
    years: 1,
    companions: ["citrus", "mulberry", "pigeon-pea"],
    nutrients: { vitaminC: 50, vitaminA: 25, fiber: 30 },
    description: "A hungry vine. Purple and yellow types. Needs a living or built trellis and a pollinator.",
    agro: "Train on mulberry, a dead post, or a wire — never on the sand. Dies to the ground in a hard freeze and often returns.",
    yields: "Fruit",
    color: "vine",
    silhouette: "vine",
  }),
  s({
    id: "chayote",
    name: "Chayote",
    latin: "Sechium edule",
    family: "Cucurbitaceae",
    layer: "vine",
    functions: ["food"],
    hz: [8, 11],
    water: "moderate",
    years: 0,
    companions: ["pigeon-pea", "corn"],
    nutrients: { fiber: 25, vitaminC: 20, folate: 20 },
    description: "A perennial cucurbit if frost is rare. One fruit is a plant.",
    agro: "Needs a stout support. Shade fruit in high heat or it gets woody. A rainy-season vine.",
    yields: "Fruit, shoots",
    color: "sage",
    silhouette: "vine",
  }),
  s({
    id: "malabar-spinach",
    name: "Malabar spinach",
    latin: "Basella alba",
    family: "Basellaceae",
    layer: "vine",
    functions: ["food"],
    hz: [8, 11],
    water: "moderate",
    years: 0,
    companions: ["citrus", "pigeon-pea"],
    nutrients: { vitaminA: 45, vitaminC: 40, iron: 25, magnesium: 20 },
    description: "The summer green that does not bolt into bitterness the way lettuce does here.",
    agro: "Train on a fence or a nurse. Self-sows in 9b. Mucilaginous when overcooked — eat it young.",
    yields: "Leaves",
    color: "ink",
    silhouette: "vine",
  }),
  s({
    id: "sweet-potato",
    name: "Sweet potato",
    latin: "Ipomoea batatas",
    family: "Convolvulaceae",
    layer: "groundcover",
    functions: ["food", "mulch"],
    hz: [8, 11],
    soils: ["sand", "loam"],
    water: "moderate",
    years: 0,
    companions: ["perennial-peanut", "citrus"],
    nutrients: { vitaminA: 85, fiber: 40, vitaminC: 30, potassium: 40, resistantStarch: 35 },
    description: "A living mulch that also feeds you. Slips in spring, roots before the rains get serious.",
    agro: "Closes sand in one season. Harvest some, leave some to cover. Weevils are the tax in old patches — rotate.",
    yields: "Roots, leaves",
    color: "coral",
    silhouette: "ground",
  }),
  s({
    id: "lemongrass",
    name: "Lemongrass",
    latin: "Cymbopogon citratus",
    family: "Poaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent", "mulch"],
    hz: [9, 11],
    water: "moderate",
    years: 0,
    companions: ["citrus", "avocado"],
    nutrients: { fiber: 10 },
    description: "A clump grass that marks a drip line and flavors a pot. Frost burns the tops; the crown usually stays.",
    agro: "Plant as a ring around young citrus. Divide in spring. Not a forage — too much oil for a flock.",
    yields: "Stalks, mulch, edge",
    color: "sage",
    silhouette: "tuft",
  }),
  s({
    id: "turmeric",
    name: "Turmeric",
    latin: "Curcuma longa",
    family: "Zingiberaceae",
    layer: "herb",
    functions: ["food", "medicine"],
    hz: [8, 11],
    sun: "part",
    water: "moderate",
    years: 0,
    companions: ["ginger", "banana", "citrus"],
    nutrients: { iron: 20, fiber: 15 },
    description: "A shade-tolerant rhizome for the understory once the canopy is honest.",
    agro: "Plant after the last cool snap. Harvest in the dry season. Loves mulch and hates a pond.",
    yields: "Rhizome",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "ginger",
    name: "Ginger",
    latin: "Zingiber officinale",
    family: "Zingiberaceae",
    layer: "herb",
    functions: ["food", "medicine"],
    hz: [8, 11],
    sun: "part",
    water: "moderate",
    years: 0,
    companions: ["turmeric", "loquat"],
    nutrients: { fiber: 10 },
    description: "Same understory logic as turmeric. A kitchen crop that wants filtered light and loose, high-organic soil.",
    agro: "Not a sand crop without a lot of compost. Raised bed or mound. Harvest late year.",
    yields: "Rhizome",
    color: "coral",
    silhouette: "herb",
  }),
  s({
    id: "pine-slash",
    name: "Slash pine",
    latin: "Pinus elliottii",
    family: "Pinaceae",
    layer: "canopy",
    edible: false,
    functions: ["timber", "windbreak", "mulch"],
    hz: [8, 10],
    soils: ["sand", "loam"],
    water: "wet",
    years: 12,
    companions: ["blueberry-south", "perennial-peanut", "oak-live"],
    description: "The flatwoods pine. Lives with a high water table and quartz sand. Needle duff acidifies a blueberry bed.",
    agro: "This is the pine that belongs on Pasco sand — not white pine. Wide spacing if you want a silvopasture understory. Longleaf is the restoration alternative; slash is the faster timber.",
    yields: "Timber, straw, windbreak",
    color: "sage",
    silhouette: "conifer",
  }),
  s({
    id: "oak-live",
    name: "Live oak",
    latin: "Quercus virginiana",
    family: "Fagaceae",
    layer: "canopy",
    edible: false,
    functions: ["timber", "fodder", "windbreak", "nurse"],
    hz: [8, 11],
    soils: ["sand", "loam", "clay"],
    water: "wet",
    years: 15,
    companions: ["pine-slash", "mulberry", "perennial-peanut", "spanish-moss"],
    fodderFor: ["pig", "cattle"],
    description: "The Gulf-coast canopy. Evergreen, hurricane-built, mast for wildlife and hogs. White oak is a northern tree; this is the one that belongs here.",
    agro: "Do not plant it on 12-foot centers and call it an orchard. Give it room. Excellent shade for livestock once the trunk can take a rub. Acorns are a mast crop, not a human staple.",
    yields: "Shade, mast, timber",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "muscadine",
    name: "Muscadine",
    latin: "Vitis rotundifolia",
    family: "Vitaceae",
    layer: "vine",
    functions: ["food"],
    hz: [7, 10],
    soils: ["sand", "loam"],
    water: "moderate",
    years: 3,
    companions: ["oak-live", "mulberry", "citrus", "passionfruit"],
    nutrients: { polyphenols: 80, anthocyanins: 55, vitaminC: 20, fiber: 25 },
    description: "The Pierce’s-disease-proof grape of the Southeast. Thick skin, bronze or black, a different wine and a better fresh fruit in 9b than vinifera.",
    agro: "Train on a living support or a two-wire trellis. Needs a pollinator unless you planted a perfect-flowered cultivar (Carlos, Noble, Supreme). Vinifera will die here; this will not.",
    yields: "Fruit",
    color: "ink",
    silhouette: "vine",
  }),
  s({
    id: "blueberry-south",
    name: "Southern highbush blueberry",
    latin: "Vaccinium spp. (southern highbush)",
    family: "Ericaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [8, 10],
    soils: ["sand"],
    water: "moderate",
    sun: "full",
    years: 2,
    companions: ["pine-slash", "bee"],
    antagonists: ["walnut-black"],
    nutrients: { vitaminC: 35, vitaminK: 40, manganese: 80, anthocyanins: 90, fiber: 40 },
    description: "Low-chill Vaccinium for central and south-central Florida. UF/IFAS prefers these from Alachua south — rabbiteye is the north-Florida berry.",
    agro: "pH 4.0–5.5, pine-bark or needles, never lime, never a wet pad without a mound. Two cultivars. This is the blueberry that belongs in Pasco, not northern highbush.",
    yields: "Fruit",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "bamboo-clump",
    name: "Clumping timber bamboo",
    latin: "Bambusa oldhamii",
    family: "Poaceae",
    layer: "canopy",
    edible: false,
    functions: ["timber", "windbreak", "mulch"],
    hz: [8, 11],
    soils: ["sand", "loam"],
    water: "wet",
    years: 4,
    companions: ["mulberry", "sesbania", "duck"],
    description: "A clumping Bambusa, not a running Phyllostachys. Timber canes and a windbreak that will not walk across the county.",
    agro: "Use this in 9b, not moso. Still needs a root barrier if you plant near a drain field. Shoots are edible if you know the species.",
    yields: "Canes, windbreak, shoots",
    color: "sage",
    silhouette: "canopy",
  }),
];
