import type {
  EcoFunction,
  Kind,
  Layer,
  Nutrients,
  PlantColor,
  RootDepth,
  Silhouette,
  Soil,
  Species,
  SunNeed,
  WaterNeed,
} from "./types";
import { chemistryHaystack } from "./chemistry";
import { NUTRIENT_BOOSTS } from "./nutrient-boosts";
import { FLORIDA_SPECIES } from "./species-florida";

type Draft = {
  id: string;
  name: string;
  latin: string;
  family: string;
  kind?: Kind;
  layer: Layer;
  edible?: boolean;
  functions: EcoFunction[];
  hz: [number, number];
  soils?: Soil[];
  water?: WaterNeed;
  sun?: SunNeed;
  root?: RootDepth;
  years?: number;
  companions?: string[];
  antagonists?: string[];
  allelopathic?: boolean;
  livestockSafe?: boolean;
  fodderFor?: string[];
  nutrients?: Nutrients;
  description: string;
  agro: string;
  yields: string;
  color: PlantColor;
  silhouette: Silhouette;
};

function s(d: Draft): Species {
  return {
    id: d.id,
    name: d.name,
    latin: d.latin,
    family: d.family,
    kind: d.kind ?? "plant",
    layer: d.layer,
    edible: d.edible ?? true,
    functions: d.functions,
    hardinessMin: d.hz[0],
    hardinessMax: d.hz[1],
    soils: d.soils ?? ["loam", "silt"],
    water: d.water ?? "moderate",
    sun: d.sun ?? "full",
    root: d.root ?? "medium",
    yearsToYield: d.years ?? 3,
    companions: d.companions ?? [],
    antagonists: d.antagonists ?? [],
    allelopathic: d.allelopathic ?? false,
    livestockSafe: d.livestockSafe ?? true,
    fodderFor: d.fodderFor ?? [],
    nutrients: d.nutrients ?? {},
    description: d.description,
    agro: d.agro,
    yields: d.yields,
    color: d.color,
    silhouette: d.silhouette,
  };
}

export const SPECIES: Species[] = [
  s({
    id: "chestnut",
    name: "Chinese chestnut",
    latin: "Castanea mollissima",
    family: "Fagaceae",
    layer: "canopy",
    functions: ["food", "timber", "fodder", "soil-builder"],
    hz: [4, 8],
    soils: ["loam", "sand", "silt", "rocky"],
    water: "moderate",
    root: "deep",
    years: 6,
    companions: ["apple", "grape", "blueberry", "alder", "bean-runner", "nasturtium", "clover-white", "chicken"],
    antagonists: ["walnut-black"],
    fodderFor: ["pig", "chicken", "sheep"],
    nutrients: { vitaminC: 40, folate: 35, potassium: 55, magnesium: 45, manganese: 70, fiber: 55, protein: 25, copper: 50, b6: 30, polyphenols: 35 },
    description: "Staple nut tree of restoration agriculture. A mature chestnut can yield more carbohydrate per acre than maize, without annual tillage.",
    agro: "Anchor of a chestnut-apple-grape guild. Wide canopy eventually shades alleys; plant nitrogen-fixing alders on the drip line and berries on the east edge. Blight-resistant Chinese and hybrid stock is the practical choice in eastern North America.",
    yields: "Nuts, coppice poles, mast for pigs",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "apple",
    name: "Apple",
    latin: "Malus domestica",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food", "fodder", "pollinator"],
    hz: [3, 8],
    soils: ["loam", "silt", "clay"],
    years: 4,
    companions: ["chestnut", "grape", "comfrey", "nasturtium", "chicken", "bee", "clover-white", "daffodil"],
    antagonists: ["walnut-black", "potato"],
    fodderFor: ["chicken", "pig", "sheep"],
    nutrients: { vitaminC: 25, fiber: 30, polyphenols: 55, flavonoids: 60, potassium: 25, vitaminK: 15 },
    description: "The classic temperate fruit. Fallen fruit is a silvopasture gift — chickens and pigs clean the orchard floor and break pest cycles.",
    agro: "Run poultry under apples: birds eat larvae in dropped fruit, scratch pests, and manure the drip line. Pair with comfrey as a chop-and-drop ring. Avoid black walnut root zones.",
    yields: "Fruit, cider, livestock mast",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "walnut-black",
    name: "Black walnut",
    latin: "Juglans nigra",
    family: "Juglandaceae",
    layer: "canopy",
    functions: ["food", "timber"],
    hz: [4, 9],
    soils: ["loam", "silt", "clay"],
    root: "deep",
    years: 8,
    companions: ["asparagus", "raspberry-black", "currant", "pawpaw", "onion"],
    antagonists: ["apple", "tomato", "potato", "pine", "blueberry", "grape"],
    allelopathic: true,
    livestockSafe: false,
    nutrients: { omega3: 70, protein: 45, magnesium: 55, manganese: 65, copper: 60, vitaminE: 40, zinc: 35, fiber: 40, polyphenols: 45 },
    description: "Highest-value temperate timber plus a rich nut. Roots exude juglone, which suppresses many plants — design around it, do not fight it.",
    agro: "Mark Shepard-style polycrop: walnuts in rows, asparagus and black raspberry in the alleys (both juglone-tolerant). Never plant tomatoes, apples, or pines beside it.",
    yields: "Nuts, veneer timber",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "walnut-english",
    name: "English walnut",
    latin: "Juglans regia",
    family: "Juglandaceae",
    layer: "canopy",
    functions: ["food"],
    hz: [5, 9],
    root: "deep",
    years: 7,
    companions: ["asparagus", "lavender", "sheep"],
    antagonists: ["apple", "tomato"],
    allelopathic: true,
    nutrients: { omega3: 75, protein: 48, magnesium: 50, manganese: 60, vitaminE: 45, copper: 55 },
    description: "Milder nut than black walnut, still mildly allelopathic. Excellent in Mediterranean alley systems.",
    agro: "Give it a wide row. Underplant only juglone-tolerant species. Sheep can graze the understory once the canopy is high.",
    yields: "Nuts",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "pecan",
    name: "Pecan",
    latin: "Carya illinoinensis",
    family: "Juglandaceae",
    layer: "canopy",
    functions: ["food", "timber"],
    hz: [6, 9],
    soils: ["loam", "silt", "clay", "sand"],
    water: "wet",
    root: "deep",
    years: 8,
    companions: ["pawpaw", "persimmon", "clover-white", "chicken", "perennial-peanut"],
    nutrients: { vitaminE: 30, zinc: 55, manganese: 70, protein: 30, fiber: 35, thiamin: 40 },
    description: "Southern staple nut. Deep taproot, long-lived, heavy mast years that fatten hogs and people alike.",
    agro: "Needs a Type I + Type II pollinator pair. In humid Florida, plant scab-tolerant southern cultivars (Elliott, Cape Fear, Lakota) and expect spray or loss in wet Junes. Poultry clean weevils. Pawpaw understory is for cooler sites — in 9b use persimmon or mulberry.",
    yields: "Nuts, timber",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "hazel",
    name: "Hazelnut",
    latin: "Corylus avellana",
    family: "Betulaceae",
    layer: "shrub",
    functions: ["food", "coppice", "windbreak"],
    hz: [4, 8],
    soils: ["loam", "silt", "clay", "sand"],
    years: 4,
    companions: ["truffle", "comfrey", "clover-white", "apple", "chicken"],
    fodderFor: ["chicken", "pig"],
    nutrients: { vitaminE: 80, copper: 70, manganese: 85, magnesium: 40, protein: 35, fiber: 40, folate: 30, thiamin: 35 },
    description: "The fastest nut crop. Coppices forever. European filbert blight-resistant hybrids are the modern orchard choice.",
    agro: "Plant as a hedgerow or multi-stem coppice. Inoculate with Burgundy or Périgord truffle mycorrhizae on calcareous soils. Excellent windbreak on the west edge of a fruit block.",
    yields: "Nuts, coppice rods, optional truffles",
    color: "mustard",
    silhouette: "shrub",
  }),
  s({
    id: "oak-white",
    name: "White oak",
    latin: "Quercus alba",
    family: "Fagaceae",
    layer: "canopy",
    edible: true,
    functions: ["food", "timber", "fodder", "soil-builder"],
    hz: [3, 9],
    soils: ["loam", "clay", "silt", "rocky"],
    root: "deep",
    years: 15,
    companions: ["truffle", "pawpaw", "morel", "pig", "sheep"],
    fodderFor: ["pig", "sheep", "cattle"],
    nutrients: { fiber: 40, potassium: 25, polyphenols: 50, manganese: 30 },
    description: "Keystone tree. Sweet acorns (low tannin) can be leached into flour. Hosts more insect life than almost any other temperate tree — which means birds, bats, and pest control.",
    agro: "Silvopasture classic: widely spaced oaks over pasture. Finish pigs on mast. White oak / hazel on limestone can host truffles. Leave standing deadwood for cavity nesters.",
    yields: "Acorns, timber, mast, truffles",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "alder",
    name: "Italian alder",
    latin: "Alnus cordata",
    family: "Betulaceae",
    layer: "canopy",
    edible: false,
    functions: ["nitrogen-fixer", "nurse", "coppice", "soil-builder", "mulch"],
    hz: [5, 8],
    soils: ["loam", "silt", "clay", "sand"],
    water: "wet",
    root: "medium",
    years: 2,
    companions: ["chestnut", "apple", "willow", "blueberry"],
    livestockSafe: true,
    description: "The temperate agroforestry nurse. Frankia actinorhizal nodules fix nitrogen without being a legume. Faster and more heat-tolerant than speckled alder, still a coppice tree — not a crop.",
    agro: "Plant as a temporary nurse among young chestnuts and apples, then coppice or ring-bark once the crop trees close canopy. Leaf litter is a free fertilizer tea. Not a Florida flatwoods tree — it wants a cooler winter.",
    yields: "Biomass, nitrogen, firewood",
    color: "sage",
    silhouette: "conifer",
  }),
  s({
    id: "black-locust",
    name: "Black locust",
    latin: "Robinia pseudoacacia",
    family: "Fabaceae",
    layer: "canopy",
    edible: false,
    functions: ["nitrogen-fixer", "timber", "fodder", "pollinator", "coppice"],
    hz: [3, 8],
    soils: ["sand", "loam", "rocky", "clay"],
    water: "dry",
    root: "deep",
    years: 3,
    companions: ["honey-locust", "clover-white", "sheep", "bee"],
    fodderFor: ["sheep", "goat", "cattle"],
    livestockSafe: false,
    description: "Rot-proof fence-post timber and a ferocious nitrogen fixer. Flowers are a major honey flow. Bark and seeds are toxic; young leaves are used as fodder in some traditions after wilting.",
    agro: "Silvopasture and living fence. Coppice on a 7–12 year rotation for posts. Keep livestock off fresh bark. Spreads by root sucker — site it where you want a colony.",
    yields: "Posts, honey, nitrogen, fodder",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "honey-locust",
    name: "Honey locust",
    latin: "Gleditsia triacanthos",
    family: "Fabaceae",
    layer: "canopy",
    functions: ["fodder", "food", "timber", "nurse"],
    hz: [4, 9],
    soils: ["loam", "clay", "sand", "rocky"],
    water: "dry",
    root: "deep",
    years: 6,
    companions: ["cattle", "sheep", "switchgrass", "clover-white"],
    fodderFor: ["cattle", "sheep", "goat", "pig"],
    nutrients: { protein: 20, fiber: 35, potassium: 25 },
    description: "Thornless selections drop sweet pods that cattle and sheep eat like candy — a living feed bunk. Open, ferny canopy lets grass grow underneath.",
    agro: "The silvopasture tree for humid temperate pasture. Plant thornless, podding cultivars on a wide grid (30–40 ft). Grass persists in the filtered light. Pods are a late-season energy supplement. Fabaceae, but it does not form agronomic rhizobial nodules — do not count it as an N-fixer.",
    yields: "Sweet pods, filtered shade",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "paulownia",
    name: "Empress tree",
    latin: "Paulownia tomentosa",
    family: "Paulowniaceae",
    layer: "canopy",
    edible: false,
    functions: ["nitrogen-fixer", "timber", "coppice", "soil-builder", "mulch"],
    hz: [6, 9],
    soils: ["loam", "sand", "silt"],
    water: "moderate",
    root: "deep",
    years: 4,
    companions: ["olive", "tomato", "fig", "eggplant"],
    description: "The alley-cropping rocket. Deep roots, huge leaves, astonishing biomass. Purple spring flowers feed bees and pull insectivorous birds into the alleys just as pests emerge.",
    agro: "Used at Quinto Sapore between olive rows: it does not compete for surface water, drops a nitrogen-rich mulch, and its flowers bring birds. Coppice for timber or keep as a tall nurse.",
    yields: "Timber, mulch, nectar",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "olive",
    name: "Olive",
    latin: "Olea europaea",
    family: "Oleaceae",
    layer: "subcanopy",
    functions: ["food", "windbreak"],
    hz: [8, 11],
    soils: ["rocky", "sand", "loam"],
    water: "dry",
    root: "deep",
    years: 5,
    companions: ["grape", "lavender", "tomato", "eggplant", "paulownia", "sheep", "rosemary"],
    nutrients: { vitaminE: 70, polyphenols: 80, iron: 25, fiber: 30, vitaminK: 20 },
    description: "The Mediterranean alley classic. Evergreen, drought-proof, and a living larder of monounsaturated fat and oleuropein.",
    agro: "Rows of olives with annual alleys (tomato, eggplant, herbs) and a nitrogen-fixing nurse (paulownia or autumn olive). Sheep graze the understory after harvest. Living pathways between alleys hold soil and water.",
    yields: "Fruit, oil, prunings",
    color: "sage",
    silhouette: "fruit",
  }),
  s({
    id: "fig",
    name: "Fig",
    latin: "Ficus carica",
    family: "Moraceae",
    layer: "subcanopy",
    functions: ["food", "fodder"],
    hz: [7, 10],
    soils: ["loam", "sand", "rocky"],
    water: "dry",
    years: 3,
    companions: ["oregano", "thyme", "lavender", "grape", "chicken"],
    fodderFor: ["chicken", "pig"],
    nutrients: { fiber: 50, potassium: 40, calcium: 30, magnesium: 25, polyphenols: 45, vitaminK: 25, b6: 20, manganese: 30 },
    description: "A generous, heat-loving fruit that asks almost nothing. Fallen figs are poultry dessert.",
    agro: "Juntos Farm pattern: figs interplanted with herb rows. The herbs suppress grass, pull pollinators, and make a second cash crop while the fig establishes.",
    yields: "Fruit, leaf fodder",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "persimmon",
    name: "American persimmon",
    latin: "Diospyros virginiana",
    family: "Ebenaceae",
    layer: "subcanopy",
    functions: ["food", "fodder"],
    hz: [4, 9],
    soils: ["loam", "clay", "sand"],
    water: "dry",
    years: 6,
    companions: ["pawpaw", "pecan", "oak-white", "chicken", "possum-grape"],
    fodderFor: ["chicken", "pig", "cattle"],
    nutrients: { vitaminA: 55, vitaminC: 40, fiber: 45, manganese: 35, polyphenols: 50 },
    description: "Native sugar-bomb that ripens after frost. Wildlife and livestock compete you for it — which is the point in a mast system.",
    agro: "Edge tree and silvopasture extra. Plant both sexes or a named grafted cultivar. Pairs with pawpaw in the oak/pecan understory.",
    yields: "Fruit, mast",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "pawpaw",
    name: "Pawpaw",
    latin: "Asimina triloba",
    family: "Annonaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [5, 8],
    soils: ["loam", "silt"],
    sun: "part",
    water: "moderate",
    years: 6,
    companions: ["oak-white", "pecan", "persimmon", "spicebush"],
    antagonists: [],
    nutrients: { vitaminC: 35, magnesium: 40, iron: 25, potassium: 40, b6: 30, riboflavin: 25 },
    description: "The largest native North American fruit. Custard texture, tropical flavor, deep shade tolerance — a true understory crop.",
    agro: "Plant in patches under high canopy. Needs a genetically different pollinator nearby (flies, not bees). Do not let it bake in full sun when young.",
    yields: "Fruit",
    color: "sage",
    silhouette: "fruit",
  }),
  s({
    id: "mulberry",
    name: "Mulberry",
    latin: "Morus alba",
    family: "Moraceae",
    layer: "subcanopy",
    functions: ["food", "fodder", "soil-builder"],
    hz: [4, 9],
    soils: ["loam", "clay", "sand"],
    water: "dry",
    years: 3,
    companions: ["chicken", "duck", "silk", "grape"],
    fodderFor: ["chicken", "pig", "sheep", "goat", "cattle", "rabbit"],
    nutrients: { vitaminC: 55, iron: 45, vitaminK: 50, fiber: 30, anthocyanins: 60, polyphenols: 55 },
    description: "The livestock tree. Leaves are a complete fodder; fruit drops for months. Chickens live under mulberries.",
    agro: "Every silvopasture should have one. Coppice for leaf hay. Plant over poultry yards — fruit falls, birds stay cool, you get dessert.",
    yields: "Fruit, leaf hay, shade",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "peach",
    name: "Peach",
    latin: "Prunus persica",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [5, 9],
    years: 3,
    companions: ["comfrey", "garlic", "nasturtium", "bee"],
    antagonists: ["walnut-black"],
    nutrients: { vitaminC: 30, vitaminA: 35, fiber: 25, potassium: 25, niacin: 20 },
    description: "Short-lived, generous stone fruit. Treat as a 12–15 year rotation crop, not an heirloom oak.",
    agro: "Underplant with garlic and comfrey. Poultry help with plum curculio if you time access after fruit set. Replace trees on a planned cycle.",
    yields: "Fruit",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "pear",
    name: "Pear",
    latin: "Pyrus communis",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food", "fodder"],
    hz: [4, 8],
    years: 5,
    companions: ["comfrey", "daffodil", "chicken", "bee"],
    fodderFor: ["pig", "chicken"],
    nutrients: { fiber: 40, vitaminC: 20, vitaminK: 25, copper: 30 },
    description: "Longer-lived than peach, fireblight-prone in humid zones. Perry pears are a farmstead beverage crop.",
    agro: "Good structural tree in a mixed orchard. Daffodil rings keep voles off the trunk. Livestock can clean drops after harvest.",
    yields: "Fruit, perry",
    color: "sage",
    silhouette: "fruit",
  }),
  s({
    id: "plum",
    name: "European plum",
    latin: "Prunus domestica",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [4, 8],
    years: 4,
    companions: ["comfrey", "garlic", "bee"],
    nutrients: { vitaminC: 25, vitaminK: 40, potassium: 30, fiber: 30, polyphenols: 40 },
    description: "Dried, it is a winter staple. Fresh, it is a July glut. Either way it belongs in a mixed stone-fruit row.",
    agro: "Plant with other Prunus for pollination. Black knot is the disease to watch. Poultry after harvest.",
    yields: "Fruit, prunes",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "cherry",
    name: "Tart cherry",
    latin: "Prunus cerasus",
    family: "Rosaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [4, 8],
    years: 4,
    companions: ["comfrey", "bee", "daffodil"],
    nutrients: { vitaminC: 30, anthocyanins: 75, polyphenols: 60, potassium: 25, fiber: 25 },
    description: "Montmorency-type cherries are a medicinal food — anthocyanins and melatonin in a pie.",
    agro: "More disease-resilient than sweet cherry in humid climates. Birds will take the crop unless you share or net.",
    yields: "Fruit",
    color: "coral",
    silhouette: "fruit",
  }),
  s({
    id: "serviceberry",
    name: "Serviceberry",
    latin: "Amelanchier alnifolia",
    family: "Rosaceae",
    layer: "shrub",
    functions: ["food", "pollinator"],
    hz: [2, 7],
    soils: ["loam", "sand", "rocky"],
    years: 3,
    companions: ["hazel", "elderberry", "bee"],
    nutrients: { vitaminC: 20, anthocyanins: 55, iron: 25, fiber: 30 },
    description: "Saskatoon. A native blueberry analog that actually likes alkaline soil and wind.",
    agro: "Hedgerow fruit. Early bloom feeds native bees before apples open. Birds take a tithe — plant extra.",
    yields: "Fruit",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "elderberry",
    name: "Elderberry",
    latin: "Sambucus canadensis",
    family: "Viburnaceae",
    layer: "shrub",
    functions: ["food", "medicine", "soil-builder"],
    hz: [3, 9],
    soils: ["loam", "silt", "clay"],
    water: "wet",
    years: 2,
    companions: ["comfrey", "nettle", "willow"],
    nutrients: { vitaminC: 60, anthocyanins: 85, flavonoids: 70, vitaminA: 30, fiber: 35, potassium: 30 },
    description: "Medicine chest and jam pot. Flowers and cooked berries; raw berries and leaves are not food.",
    agro: "Wet edge, swale berm, or poultry-yard hedge. Coppices. Pairs with comfrey and nettle as a medicinal guild.",
    yields: "Flowers, cooked berries, dye",
    color: "ink",
    silhouette: "shrub",
  }),
  s({
    id: "blueberry",
    name: "Northern highbush blueberry",
    latin: "Vaccinium corymbosum",
    family: "Ericaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [4, 7],
    soils: ["sand", "loam"],
    water: "wet",
    sun: "full",
    years: 3,
    companions: ["pine", "chestnut", "pine-needles", "bee"],
    antagonists: ["walnut-black"],
    nutrients: { vitaminC: 35, vitaminK: 40, manganese: 80, anthocyanins: 90, fiber: 40, vitaminE: 20 },
    description: "Northern acid-soil berry. Needs winter chill and a fungal soil. This is not the Florida blueberry — southern highbush is.",
    agro: "Under the east drip line of white pine or chestnut, mulched with needles. Never lime. Two cultivars for pollination. Fails south of about zone 7 without chill.",
    yields: "Fruit",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "raspberry",
    name: "Red raspberry",
    latin: "Rubus idaeus",
    family: "Rosaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [3, 8],
    sun: "part",
    years: 1,
    companions: ["garlic", "comfrey", "apple"],
    antagonists: ["blackberry", "potato"],
    nutrients: { vitaminC: 50, manganese: 60, fiber: 45, anthocyanins: 50, vitaminK: 20 },
    description: "Cane fruit that colonizes edges. Primocane types fruit the first year.",
    agro: "Orchard edge, not the alley center. Trellis or let it become a wildlife hedge. Rotate out after 8–10 years to dodge viruses.",
    yields: "Fruit, leaf tea",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "raspberry-black",
    name: "Black raspberry",
    latin: "Rubus occidentalis",
    family: "Rosaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [4, 8],
    sun: "part",
    years: 1,
    companions: ["walnut-black", "asparagus"],
    nutrients: { anthocyanins: 80, vitaminC: 40, fiber: 40, manganese: 50 },
    description: "One of the few fruits that tolerate walnut juglone. Intense berry.",
    agro: "The crop to put in a black-walnut alley with asparagus. Tip-rooting canes will wander — mow a path.",
    yields: "Fruit",
    color: "ink",
    silhouette: "shrub",
  }),
  s({
    id: "blackberry",
    name: "Blackberry",
    latin: "Rubus allegheniensis",
    family: "Rosaceae",
    layer: "shrub",
    functions: ["food", "windbreak"],
    hz: [5, 9],
    years: 1,
    companions: ["comfrey", "garlic"],
    antagonists: ["raspberry"],
    nutrients: { vitaminC: 40, vitaminK: 45, manganese: 55, fiber: 45, anthocyanins: 65 },
    description: "Thorny living fence that pays rent in fruit. Thornless cultivars exist if you value shins.",
    agro: "Perimeter defense and bird habitat. Keep it out of the raspberry patch (they share diseases).",
    yields: "Fruit, hedge",
    color: "ink",
    silhouette: "shrub",
  }),
  s({
    id: "currant",
    name: "Black currant",
    latin: "Ribes nigrum",
    family: "Grossulariaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [3, 7],
    sun: "part",
    years: 2,
    companions: ["walnut-black", "gooseberry", "comfrey"],
    nutrients: { vitaminC: 95, anthocyanins: 70, potassium: 30, fiber: 30 },
    description: "Vitamin C bomb. Banned in parts of the US historically because of white pine blister rust — check your state, plant rust-resistant cultivars.",
    agro: "Shade-tolerant orchard understory. Juglone-tolerant enough for walnut edges. Magnificent jam.",
    yields: "Fruit",
    color: "ink",
    silhouette: "shrub",
  }),
  s({
    id: "gooseberry",
    name: "Gooseberry",
    latin: "Ribes uva-crispa",
    family: "Grossulariaceae",
    layer: "shrub",
    functions: ["food"],
    hz: [3, 7],
    sun: "part",
    years: 2,
    companions: ["currant", "comfrey"],
    nutrients: { vitaminC: 55, fiber: 40, vitaminA: 20 },
    description: "Tart northern berry that thrives in cool shade. Pie fruit.",
    agro: "North side of a fruit row, or walnut understory. Prune to an open goblet to keep mildew down.",
    yields: "Fruit",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "aronia",
    name: "Aronia",
    latin: "Aronia melanocarpa",
    family: "Rosaceae",
    layer: "shrub",
    functions: ["food", "medicine"],
    hz: [3, 8],
    soils: ["loam", "clay", "silt", "sand"],
    water: "wet",
    years: 3,
    companions: ["elderberry", "willow"],
    nutrients: { anthocyanins: 100, polyphenols: 95, vitaminC: 30, vitaminK: 35, fiber: 35 },
    description: "Chokeberry. Possibly the highest-anthocyanin temperate fruit. Astringent raw, superb as juice or dried.",
    agro: "Wet swale or rain garden that also pays. Almost pest-free. Process the fruit — nobody snacks on it.",
    yields: "Fruit, juice",
    color: "ink",
    silhouette: "shrub",
  }),
  s({
    id: "sea-buckthorn",
    name: "Sea buckthorn",
    latin: "Hippophae rhamnoides",
    family: "Elaeagnaceae",
    layer: "shrub",
    functions: ["food", "nitrogen-fixer", "medicine", "windbreak"],
    hz: [3, 7],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 4,
    companions: ["goumi", "apple"],
    nutrients: { vitaminC: 100, vitaminE: 55, carotenoids: 70, omega3: 25, flavonoids: 60, vitaminA: 40 },
    description: "Actinorhizal nitrogen fixer whose berries are a vitamin C supernova and a source of rare palmitoleic oil.",
    agro: "Thorny windbreak on poor, dry, windy ground. Plant both sexes. Harvest is a fight — freeze-and-beat or use a dedicated comb.",
    yields: "Berries, oil, nitrogen",
    color: "mustard",
    silhouette: "shrub",
  }),
  s({
    id: "goumi",
    name: "Goumi",
    latin: "Elaeagnus multiflora",
    family: "Elaeagnaceae",
    layer: "shrub",
    functions: ["food", "nitrogen-fixer", "nurse"],
    hz: [5, 8],
    soils: ["sand", "loam", "clay", "rocky"],
    water: "dry",
    years: 3,
    companions: ["apple", "chestnut", "autumn-olive"],
    nutrients: { vitaminC: 45, carotenoids: 50, vitaminA: 30, fiber: 25 },
    description: "The well-behaved cousin of autumn olive. Tart cherry-like fruit, nitrogen fixer, not invasive in most of its range.",
    agro: "Nurse shrub on the sunny side of young fruit trees. Fruit is excellent leather and jam. Birds plant the seeds — watch fencerows.",
    yields: "Fruit, nitrogen",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "autumn-olive",
    name: "Autumn olive",
    latin: "Elaeagnus umbellata",
    family: "Elaeagnaceae",
    layer: "shrub",
    edible: true,
    functions: ["food", "nitrogen-fixer", "nurse"],
    hz: [4, 8],
    soils: ["sand", "loam", "rocky", "clay"],
    water: "dry",
    years: 3,
    companions: ["chestnut", "apple"],
    nutrients: { carotenoids: 90, vitaminC: 40, vitaminA: 35, flavonoids: 50 },
    description: "Invasive in much of eastern North America — and also a nitrogen-fixing, lycopene-rich fruit. Use only where it is already naturalized, or skip it.",
    agro: "If it is already on the land, manage it as a chop-and-drop nurse and a late-season fruit, rather than pretending it is not there. Do not introduce it to a clean site.",
    yields: "Fruit, nitrogen, mulch",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "grape",
    name: "Grape",
    latin: "Vitis vinifera",
    family: "Vitaceae",
    layer: "vine",
    functions: ["food"],
    hz: [5, 9],
    soils: ["loam", "sand", "rocky"],
    water: "dry",
    years: 3,
    companions: ["chestnut", "apple", "fig", "clover-white"],
    antagonists: ["walnut-black"],
    nutrients: { vitaminC: 15, vitaminK: 35, copper: 30, polyphenols: 70, flavonoids: 65, potassium: 20 },
    description: "Vertical calories. Grown up a tree trunk it costs no extra ground — the living trellis of classical agroforestry.",
    agro: "Train up chestnut or apple trunks. Vinifera fails in humid 9b (Pierce’s disease). Use Concord/labrusca in the mid-Atlantic; use muscadine on the Gulf.",
    yields: "Fruit, leaves, vine prunings",
    color: "ink",
    silhouette: "vine",
  }),
  s({
    id: "kiwi",
    name: "Hardy kiwi",
    latin: "Actinidia arguta",
    family: "Actinidiaceae",
    layer: "vine",
    functions: ["food"],
    hz: [4, 8],
    sun: "part",
    years: 4,
    companions: ["apple"],
    nutrients: { vitaminC: 85, vitaminE: 35, vitaminK: 50, fiber: 30, potassium: 30 },
    description: "Grape-sized kiwi you eat whole. Explosive vitamin C. Needs a male vine nearby.",
    agro: "Strong trellis or a sacrificed nurse tree. Shade the roots, sun the canopy. One male per six to eight females.",
    yields: "Fruit",
    color: "sage",
    silhouette: "vine",
  }),
  s({
    id: "hops",
    name: "Hops",
    latin: "Humulus lupulus",
    family: "Cannabaceae",
    layer: "vine",
    edible: true,
    functions: ["food", "medicine"],
    hz: [4, 8],
    years: 2,
    companions: ["apple"],
    nutrients: { fiber: 20, polyphenols: 40 },
    description: "Bittering flower and a vigorous perennial vine. Shoots are a spring vegetable.",
    agro: "North-side screen or dedicated hop yard. Dies to the ground each winter. Do not let it swallow a young fruit tree.",
    yields: "Cones, spring shoots",
    color: "sage",
    silhouette: "vine",
  }),
  s({
    id: "bean-runner",
    name: "Scarlet runner bean",
    latin: "Phaseolus coccineus",
    family: "Fabaceae",
    layer: "vine",
    functions: ["food", "nitrogen-fixer", "pollinator"],
    hz: [3, 9],
    years: 0,
    companions: ["chestnut", "corn", "nasturtium", "squash"],
    nutrients: { protein: 55, fiber: 50, folate: 60, iron: 40, magnesium: 35 },
    description: "Perennial in zone 7+, treated as an annual elsewhere. Hummingbird magnet and a climbing nitrogen fixer.",
    agro: "Grow up young tree trunks and sunflower stalks. The video's chestnut guild uses beans to feed the soil while the trees are still small.",
    yields: "Beans, flowers, nitrogen",
    color: "coral",
    silhouette: "vine",
  }),
  s({
    id: "nasturtium",
    name: "Nasturtium",
    latin: "Tropaeolum majus",
    family: "Tropaeolaceae",
    layer: "vine",
    functions: ["food", "pest-deterrent", "pollinator"],
    hz: [9, 11],
    years: 0,
    companions: ["apple", "chestnut", "tomato", "squash", "bean-runner"],
    nutrients: { vitaminC: 70, carotenoids: 40 },
    description: "Entirely edible trap crop. Aphids prefer it to your fruit trees. Peppery leaves and flowers.",
    agro: "The pest-deflection ring in the chestnut-apple guild. Self-sows. Let it scramble under trees and through alleys.",
    yields: "Leaves, flowers, seed capers",
    color: "mustard",
    silhouette: "vine",
  }),
  s({
    id: "asparagus",
    name: "Asparagus",
    latin: "Asparagus officinalis",
    family: "Asparagaceae",
    layer: "herb",
    functions: ["food"],
    hz: [3, 8],
    soils: ["loam", "sand", "silt"],
    years: 3,
    companions: ["walnut-black", "tomato", "parsley", "raspberry-black"],
    antagonists: [],
    nutrients: { vitaminK: 70, folate: 55, vitaminA: 20, iron: 20, fiber: 25 },
    description: "A 20-year perennial vegetable that happens to tolerate juglone. Spring cash crop while canopy trees are young.",
    agro: "The classic walnut polycrop alley. Spears in April, ferns all summer that nurse the soil. Do not harvest the first two years.",
    yields: "Spears",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "comfrey",
    name: "Comfrey",
    latin: "Symphytum × uplandicum",
    family: "Boraginaceae",
    layer: "herb",
    edible: false,
    functions: ["dynamic-accumulator", "mulch", "fodder", "medicine", "soil-builder"],
    hz: [3, 9],
    soils: ["loam", "clay", "silt", "sand"],
    water: "moderate",
    years: 1,
    companions: ["apple", "chestnut", "hazel", "elderberry"],
    fodderFor: ["chicken", "pig", "sheep"],
    livestockSafe: true,
    description: "Bocking 14, the sterile workhorse. Mines potassium, calcium, and silica from the subsoil and dumps it as mulch four times a season.",
    agro: "A ring around every fruit tree. Chop-and-drop. Sterile cultivars only — true comfrey seeds itself into a problem. Poultry love the leaves.",
    yields: "Mulch, foliar tea, fodder",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "nettle",
    name: "Stinging nettle",
    latin: "Urtica dioica",
    family: "Urticaceae",
    layer: "herb",
    functions: ["food", "dynamic-accumulator", "medicine", "fodder"],
    hz: [3, 9],
    water: "wet",
    sun: "part",
    years: 1,
    companions: ["elderberry", "comfrey", "willow"],
    fodderFor: ["chicken", "goat"],
    nutrients: { vitaminA: 70, vitaminC: 50, vitaminK: 80, iron: 65, calcium: 60, magnesium: 45, protein: 40 },
    description: "Mineral-dense wild green. The sting is a harvesting tax; cooked or dried it is spinach's more nutritious cousin.",
    agro: "Wet edge and compost activator. Dynamic accumulator of iron and calcium. Feed wilted leaves to poultry. Keep it out of paths.",
    yields: "Greens, tea, fiber, fodder",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "yarrow",
    name: "Yarrow",
    latin: "Achillea millefolium",
    family: "Asteraceae",
    layer: "herb",
    edible: false,
    functions: ["dynamic-accumulator", "pollinator", "medicine", "pest-deterrent"],
    hz: [3, 9],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 1,
    companions: ["apple", "lavender", "oregano"],
    description: "Umbel that pulls hoverflies and parasitic wasps into the orchard. Accumulates copper, potash, phosphates.",
    agro: "Path edge and orchard understory. A key insectary plant. Drought-proof once established.",
    yields: "Flowers, insectary services",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "echinacea",
    name: "Echinacea",
    latin: "Echinacea purpurea",
    family: "Asteraceae",
    layer: "herb",
    edible: false,
    functions: ["medicine", "pollinator"],
    hz: [3, 8],
    water: "dry",
    years: 2,
    companions: ["yarrow", "bee"],
    description: "Prairie medicine and a late-summer nectar station.",
    agro: "Orchard edge and pollinator strip. Goldfinches take the seed.",
    yields: "Root, flower",
    color: "coral",
    silhouette: "herb",
  }),
  s({
    id: "borage",
    name: "Borage",
    latin: "Borago officinalis",
    family: "Boraginaceae",
    layer: "herb",
    functions: ["food", "pollinator", "dynamic-accumulator"],
    hz: [3, 10],
    years: 0,
    companions: ["tomato", "squash", "strawberry"],
    nutrients: { vitaminC: 30, omega3: 20 },
    description: "Cucumber-flavored flower that bees refuse to leave. Self-sows forever if you let it.",
    agro: "Alley insectary. Said to deter tomato hornworm and improve strawberry flavor — plant it and decide for yourself.",
    yields: "Flowers, leaves, bee forage",
    color: "vine",
    silhouette: "herb",
  }),
  s({
    id: "oregano",
    name: "Oregano",
    latin: "Origanum vulgare",
    family: "Lamiaceae",
    layer: "groundcover",
    functions: ["food", "pest-deterrent", "pollinator"],
    hz: [5, 10],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 1,
    companions: ["fig", "olive", "tomato", "thyme"],
    nutrients: { vitaminK: 55, iron: 30, polyphenols: 70, vitaminA: 20 },
    description: "Living mulch that tastes like a pizza. Antimicrobial oils help in the henhouse too.",
    agro: "Fig and olive understory. Shear after bloom. Spreads into a fragrant carpet that outcompetes grass.",
    yields: "Herb",
    color: "sage",
    silhouette: "ground",
  }),
  s({
    id: "thyme",
    name: "Thyme",
    latin: "Thymus vulgaris",
    family: "Lamiaceae",
    layer: "groundcover",
    functions: ["food", "pest-deterrent", "pollinator"],
    hz: [5, 9],
    soils: ["sand", "rocky", "loam"],
    water: "dry",
    years: 1,
    companions: ["fig", "olive", "rosemary"],
    nutrients: { vitaminC: 25, iron: 30, vitaminA: 20 },
    description: "Tiny-leaved carpet for hot, dry stone edges.",
    agro: "Path cracks, rock mulch, and the south side of Mediterranean trees.",
    yields: "Herb",
    color: "sage",
    silhouette: "ground",
  }),
  s({
    id: "rosemary",
    name: "Rosemary",
    latin: "Salvia rosmarinus",
    family: "Lamiaceae",
    layer: "shrub",
    functions: ["food", "pest-deterrent"],
    hz: [8, 11],
    soils: ["sand", "rocky", "loam"],
    water: "dry",
    years: 1,
    companions: ["olive", "lavender", "thyme"],
    nutrients: { iron: 25, fiber: 20 },
    description: "Evergreen culinary shrub for the warm-winter farm.",
    agro: "Mediterranean guild with olive, lavender, thyme. Deer usually leave it alone.",
    yields: "Herb",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "lavender",
    name: "Lavender",
    latin: "Lavandula angustifolia",
    family: "Lamiaceae",
    layer: "shrub",
    edible: true,
    functions: ["medicine", "pollinator", "pest-deterrent"],
    hz: [5, 9],
    soils: ["sand", "rocky", "loam"],
    water: "dry",
    years: 2,
    companions: ["olive", "grape", "apple", "bee", "sheep"],
    description: "Insectary, deer-repellent, and a cash bouquet crop. Sheep will not eat it if there is grass.",
    agro: "Alley edge and understory in dry orchards. Excellent around beehives.",
    yields: "Flowers, oil",
    color: "vine",
    silhouette: "shrub",
  }),
  s({
    id: "mint",
    name: "Peppermint",
    latin: "Mentha × piperita",
    family: "Lamiaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent", "medicine"],
    hz: [3, 9],
    water: "wet",
    sun: "part",
    years: 1,
    companions: ["cabbage"],
    antagonists: [],
    nutrients: { vitaminA: 30, manganese: 25 },
    description: "Contain it or it will own the farm. Wonderful where you want it.",
    agro: "Sink it in a buried trough, or give it a wet waste corner. Mice dislike the smell around storage.",
    yields: "Herb, tea",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "sage",
    name: "Culinary sage",
    latin: "Salvia officinalis",
    family: "Lamiaceae",
    layer: "shrub",
    functions: ["food", "pollinator", "pest-deterrent"],
    hz: [5, 9],
    water: "dry",
    years: 1,
    companions: ["rosemary", "cabbage"],
    nutrients: { vitaminK: 50, iron: 20 },
    description: "Soft woody herb. Bees work the blue flowers in late spring.",
    agro: "Dry orchard edge. Replace plants every four years as they go woody.",
    yields: "Leaves",
    color: "sage",
    silhouette: "shrub",
  }),
  s({
    id: "clover-white",
    name: "White clover",
    latin: "Trifolium repens",
    family: "Fabaceae",
    layer: "groundcover",
    functions: ["nitrogen-fixer", "forage", "pollinator", "soil-builder"],
    hz: [3, 10],
    soils: ["loam", "clay", "silt", "sand"],
    years: 0,
    companions: ["apple", "chestnut", "grape", "chicken", "sheep", "bee"],
    fodderFor: ["sheep", "cattle", "chicken", "rabbit"],
    nutrients: { protein: 30 },
    description: "The living carpet of temperate agroforestry. Fixes nitrogen, feeds bees, feeds livestock, outcompetes many weeds.",
    agro: "Default orchard floor and silvopasture understory. Dutch white under trees; ladino in pasture. Do not let it go rank before grazing or it mats.",
    yields: "Nitrogen, forage, honey",
    color: "sage",
    silhouette: "ground",
  }),
  s({
    id: "clover-red",
    name: "Red clover",
    latin: "Trifolium pratense",
    family: "Fabaceae",
    layer: "herb",
    functions: ["nitrogen-fixer", "forage", "medicine", "soil-builder"],
    hz: [3, 8],
    years: 0,
    companions: ["grass", "apple"],
    fodderFor: ["cattle", "sheep"],
    nutrients: { protein: 35, calcium: 25, flavonoids: 40 },
    description: "Deeper-rooted than white clover, a short-lived perennial used in pasture mixes and as a plowdown.",
    agro: "Alley cover and pasture. A biennial habit — overseed every other year. Bloat risk for cattle on pure stands.",
    yields: "Forage, nitrogen, flowers",
    color: "coral",
    silhouette: "herb",
  }),
  s({
    id: "strawberry",
    name: "Alpine strawberry",
    latin: "Fragaria vesca",
    family: "Rosaceae",
    layer: "groundcover",
    functions: ["food"],
    hz: [4, 8],
    sun: "part",
    years: 1,
    companions: ["borage", "apple", "garlic"],
    nutrients: { vitaminC: 70, manganese: 40, folate: 20, anthocyanins: 30 },
    description: "Small, intense berries that run into a fruiting mulch.",
    agro: "Orchard understory on the sunny edge. Alpine types stay in clumps; garden types runner. Refresh beds every three years.",
    yields: "Fruit",
    color: "coral",
    silhouette: "ground",
  }),
  s({
    id: "daikon",
    name: "Daikon radish",
    latin: "Raphanus sativus",
    family: "Brassicaceae",
    layer: "root",
    functions: ["food", "soil-builder"],
    hz: [2, 10],
    years: 0,
    companions: ["apple"],
    nutrients: { vitaminC: 40, folate: 25, potassium: 25 },
    description: "A living subsoiler. The taproot punches plowpan, then rots into a drainage hole full of organic matter.",
    agro: "Sow in new alleys and compacted lanes in late summer. Leave the roots to winter-kill. Eat the extras.",
    yields: "Roots, soil pores",
    color: "bark",
    silhouette: "tuft",
  }),
  s({
    id: "sunchoke",
    name: "Jerusalem artichoke",
    latin: "Helianthus tuberosus",
    family: "Asteraceae",
    layer: "root",
    functions: ["food", "fodder", "windbreak"],
    hz: [3, 8],
    years: 1,
    companions: ["squash"],
    fodderFor: ["pig"],
    nutrients: { iron: 40, potassium: 45, fiber: 30, thiamin: 30 },
    description: "Inulin-rich tuber that will colonize a county if you let it. Pigs are the harvest tool.",
    agro: "Contain with a deep path or give a pig paddock a patch and let them dig. Nine-foot stems are a summer windbreak.",
    yields: "Tubers, pig forage",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "garlic",
    name: "Garlic",
    latin: "Allium sativum",
    family: "Amaryllidaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent", "medicine"],
    hz: [3, 8],
    years: 1,
    companions: ["apple", "peach", "raspberry", "rose"],
    antagonists: ["pea", "bean-runner"],
    nutrients: { vitaminC: 25, manganese: 40, b6: 25, selenium: 30 },
    description: "Orchard allium. Sulfur compounds bother borers and rodents; the bulbs pay the rent.",
    agro: "Ring stone fruit and cane fruit. Plant in autumn, harvest in early summer before the canopy closes.",
    yields: "Bulbs, scapes",
    color: "sage",
    silhouette: "tuft",
  }),
  s({
    id: "onion",
    name: "Walking onion",
    latin: "Allium × proliferum",
    family: "Amaryllidaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent"],
    hz: [3, 9],
    years: 1,
    companions: ["walnut-black", "carrot"],
    nutrients: { vitaminC: 20, b6: 20 },
    description: "Perennial onion that plants itself. Topsets walk to new ground.",
    agro: "Juglone-tolerant enough for walnut edges. A permanent allium presence without replanting.",
    yields: "Greens, bulbils",
    color: "sage",
    silhouette: "tuft",
  }),
  s({
    id: "tomato",
    name: "Tomato",
    latin: "Solanum lycopersicum",
    family: "Solanaceae",
    layer: "herb",
    functions: ["food"],
    hz: [4, 11],
    years: 0,
    companions: ["olive", "basil", "borage", "asparagus", "paulownia"],
    antagonists: ["walnut-black", "potato", "fennel"],
    nutrients: { vitaminC: 45, carotenoids: 80, vitaminA: 30, potassium: 30 },
    description: "The alley annual. In a young olive or fruit system it pays the bills for the first decade.",
    agro: "Quinto Sapore pattern: tomatoes and eggplants in the alleys between olive rows, with living pathways and a paulownia nurse. Pull them out of walnut root zones.",
    yields: "Fruit",
    color: "coral",
    silhouette: "herb",
  }),
  s({
    id: "eggplant",
    name: "Eggplant",
    latin: "Solanum melongena",
    family: "Solanaceae",
    layer: "herb",
    functions: ["food"],
    hz: [5, 11],
    years: 0,
    companions: ["olive", "tomato", "paulownia"],
    antagonists: ["walnut-black"],
    nutrients: { fiber: 30, potassium: 25, manganese: 20 },
    description: "Heat-loving alley crop that loves the reflected warmth of a Mediterranean tree row.",
    agro: "Same alley as tomato. Benefits from the windbreak of the tree rows.",
    yields: "Fruit",
    color: "ink",
    silhouette: "herb",
  }),
  s({
    id: "squash",
    name: "Winter squash",
    latin: "Cucurbita moschata",
    family: "Cucurbitaceae",
    layer: "groundcover",
    functions: ["food"],
    hz: [3, 10],
    years: 0,
    companions: ["corn", "bean-runner", "nasturtium"],
    nutrients: { vitaminA: 90, vitaminC: 30, fiber: 35, potassium: 30 },
    description: "Living mulch that smothers weeds and stores as winter calories.",
    agro: "Three sisters alley, or a living carpet under young widely spaced trees before the canopy closes.",
    yields: "Fruit",
    color: "mustard",
    silhouette: "ground",
  }),
  s({
    id: "corn",
    name: "Flint corn",
    latin: "Zea mays",
    family: "Poaceae",
    layer: "herb",
    functions: ["food"],
    hz: [4, 9],
    years: 0,
    companions: ["bean-runner", "squash"],
    nutrients: { fiber: 25, magnesium: 25, b6: 20 },
    description: "The plant agroforestry is trying to stop you from growing as a monoculture — and a fine member of a diverse alley.",
    agro: "Use it as a seasonal trellis for beans in a young tree system, then retire the corn rows as canopy closes. Never as the whole farm.",
    yields: "Grain",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "sunflower",
    name: "Sunflower",
    latin: "Helianthus annuus",
    family: "Asteraceae",
    layer: "herb",
    functions: ["food", "fodder"],
    hz: [3, 9],
    years: 0,
    companions: ["bean-runner", "squash"],
    fodderFor: ["chicken"],
    nutrients: { vitaminE: 75, selenium: 40, copper: 35, protein: 30 },
    description: "Instant trellis and a seed crop chickens will harvest themselves.",
    agro: "Alley annual. After heads ripen, toss them into the poultry yard.",
    yields: "Seed, bird feed",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "buckwheat",
    name: "Buckwheat",
    latin: "Fagopyrum esculentum",
    family: "Polygonaceae",
    layer: "herb",
    functions: ["food", "pollinator", "soil-builder"],
    hz: [3, 9],
    years: 0,
    companions: ["bee"],
    nutrients: { magnesium: 40, fiber: 30, protein: 25, manganese: 30 },
    description: "40-day cover that smothers weeds, feeds bees, and loosens soil. The grain is a bonus.",
    agro: "Emergency cover in any bare alley. Terminate at flowering for a quick mulch, or let it seed if you want it back.",
    yields: "Grain, nectar, cover",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "rye",
    name: "Cereal rye",
    latin: "Secale cereale",
    family: "Poaceae",
    layer: "herb",
    edible: true,
    functions: ["soil-builder", "food"],
    hz: [3, 8],
    years: 0,
    companions: ["vetch"],
    description: "Winter sponge for nutrients and a spring mulch. Allelopathic to small seeds — useful and a little dangerous.",
    agro: "Sow in autumn alleys. Crimp or scythe before planting summer crops. Do not undersow tiny seeds into fresh rye residue.",
    yields: "Grain, mulch",
    color: "mustard",
    silhouette: "tuft",
  }),
  s({
    id: "basil",
    name: "Basil",
    latin: "Ocimum basilicum",
    family: "Lamiaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent"],
    hz: [9, 11],
    years: 0,
    companions: ["tomato"],
    nutrients: { vitaminK: 45, vitaminA: 25 },
    description: "The tomato's best friend in the alley.",
    agro: "Tuck into tomato beds. Successive sowings.",
    yields: "Herb",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "willow",
    name: "Willow",
    latin: "Salix viminalis",
    family: "Salicaceae",
    layer: "canopy",
    edible: false,
    functions: ["coppice", "fodder", "soil-builder", "medicine"],
    hz: [2, 8],
    soils: ["silt", "clay", "loam", "sand"],
    water: "wet",
    years: 1,
    companions: ["alder", "elderberry", "duck", "goat"],
    fodderFor: ["goat", "sheep"],
    description: "The riparian engine. Coppices for basketry and biomass, holds banks, and is a mineral-rich browse.",
    agro: "Swales, ditches, and pond edges. Goat browse. Living fences. Do not plant it where you will later want a septic field.",
    yields: "Rods, browse, salicylates",
    color: "sage",
    silhouette: "conifer",
  }),
  s({
    id: "pine",
    name: "White pine",
    latin: "Pinus strobus",
    family: "Pinaceae",
    layer: "canopy",
    edible: false,
    functions: ["timber", "windbreak", "mulch"],
    hz: [3, 8],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 15,
    companions: ["blueberry", "chanterelle"],
    antagonists: ["walnut-black"],
    description: "Needle mulch acidifies; the timber is light and true. A windbreak on the north and west.",
    agro: "A northern windbreak and blueberry nurse — not a Gulf-coast tree. White pine declines in 9b heat and humidity. For Pasco flatwoods use slash or longleaf.",
    yields: "Timber, needles, nuts (modest)",
    color: "sage",
    silhouette: "conifer",
  }),
  s({
    id: "cedar",
    name: "Eastern red cedar",
    latin: "Juniperus virginiana",
    family: "Cupressaceae",
    layer: "canopy",
    edible: false,
    functions: ["windbreak", "timber"],
    hz: [3, 9],
    soils: ["rocky", "sand", "loam", "clay"],
    water: "dry",
    years: 10,
    companions: [],
    description: "Pioneer juniper. Rot-resistant posts and a dense windbreak. Host of cedar-apple rust — keep it away from apples.",
    agro: "Windbreak on the property line, never beside the apple block. Wildlife hedge.",
    yields: "Posts, berries (gin)",
    color: "ink",
    silhouette: "conifer",
  }),
  s({
    id: "maple",
    name: "Sugar maple",
    latin: "Acer saccharum",
    family: "Sapindaceae",
    layer: "canopy",
    functions: ["food", "timber"],
    hz: [3, 8],
    soils: ["loam", "silt"],
    years: 20,
    companions: ["morel"],
    nutrients: { manganese: 20 },
    description: "The long game. A sugarbush is a farm enterprise that outlives you.",
    agro: "Dedicated grove, not mixed into a fruit alley. Morels sometimes fruit in the duff. Tap after 12 inches DBH.",
    yields: "Sap, timber",
    color: "coral",
    silhouette: "canopy",
  }),
  s({
    id: "bamboo",
    name: "Timber bamboo",
    latin: "Phyllostachys edulis",
    family: "Poaceae",
    layer: "canopy",
    functions: ["food", "timber", "windbreak"],
    hz: [6, 10],
    water: "moderate",
    years: 4,
    companions: [],
    nutrients: { fiber: 25, potassium: 25, protein: 15 },
    description: "Running timber. Contain it with a 30-inch rhizome barrier or a water ditch, or do not plant it.",
    agro: "Dedicated grove for poles and spring shoots. Never next to a neighbor you like.",
    yields: "Culms, shoots",
    color: "sage",
    silhouette: "conifer",
  }),
  s({
    id: "pomegranate",
    name: "Pomegranate",
    latin: "Punica granatum",
    family: "Lythraceae",
    layer: "shrub",
    functions: ["food", "medicine"],
    hz: [8, 11],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 4,
    companions: ["olive", "fig", "lavender"],
    nutrients: { vitaminC: 35, vitaminK: 45, polyphenols: 85, potassium: 30, folate: 20 },
    description: "Punicalagin-rich fruit of hot, dry orchards. A shrub that can be trained as a small tree.",
    agro: "Mediterranean guild. Punches above its weight in antioxidant score.",
    yields: "Arils, juice",
    color: "coral",
    silhouette: "shrub",
  }),
  s({
    id: "jujube",
    name: "Jujube",
    latin: "Ziziphus jujuba",
    family: "Rhamnaceae",
    layer: "subcanopy",
    functions: ["food"],
    hz: [6, 10],
    soils: ["sand", "loam", "rocky"],
    water: "dry",
    years: 4,
    companions: ["olive", "pomegranate"],
    nutrients: { vitaminC: 80, potassium: 30, fiber: 40 },
    description: "Chinese date. Drought-proof, pest-light, tastes like a crisp apple then a date.",
    agro: "Hot, dry edge. Almost no spray program. Suckers from the rootstock — mow them or you have a thicket.",
    yields: "Fruit",
    color: "mustard",
    silhouette: "fruit",
  }),
  s({
    id: "mesquite",
    name: "Honey mesquite",
    latin: "Prosopis glandulosa",
    family: "Fabaceae",
    layer: "canopy",
    functions: ["food", "nitrogen-fixer", "fodder", "timber"],
    hz: [7, 11],
    soils: ["sand", "rocky", "loam"],
    water: "dry",
    root: "deep",
    years: 5,
    companions: ["cattle", "sheep"],
    fodderFor: ["cattle", "sheep", "goat"],
    nutrients: { protein: 40, fiber: 45, calcium: 25, iron: 30 },
    description: "Desert staple. Pod flour is a complete-feeling wild grain. Roots drink from aquifers you cannot reach.",
    agro: "Arid silvopasture. Pods fatten cattle. Do not introduce where it is a regulated weed.",
    yields: "Pods, honey, nitrogen",
    color: "mustard",
    silhouette: "canopy",
  }),
  s({
    id: "switchgrass",
    name: "Switchgrass",
    latin: "Panicum virgatum",
    family: "Poaceae",
    layer: "herb",
    edible: false,
    functions: ["forage", "soil-builder"],
    hz: [3, 9],
    soils: ["sand", "loam", "clay"],
    water: "dry",
    years: 1,
    companions: ["honey-locust", "cattle", "sheep"],
    fodderFor: ["cattle", "sheep"],
    description: "Deep-rooted prairie grass that holds soil and yields summer forage under a high, open canopy.",
    agro: "The pasture half of a honey-locust silvopasture. Burns or grazes on a rest rotation.",
    yields: "Forage, biomass",
    color: "mustard",
    silhouette: "tuft",
  }),
  s({
    id: "chicory",
    name: "Forage chicory",
    latin: "Cichorium intybus",
    family: "Asteraceae",
    layer: "herb",
    functions: ["forage", "medicine", "dynamic-accumulator"],
    hz: [3, 8],
    years: 1,
    companions: ["sheep", "cattle", "clover-white"],
    fodderFor: ["sheep", "cattle"],
    nutrients: { vitaminK: 30, fiber: 40 },
    description: "Deep taproot, anthelmintic forage, mineral miner. Sheep stay healthier on a chicory mix.",
    agro: "Pasture mix with clover and grass. Condensed tannins help with internal parasites.",
    yields: "Forage, roots",
    color: "vine",
    silhouette: "herb",
  }),
  s({
    id: "plantain-forage",
    name: "Narrowleaf plantain",
    latin: "Plantago lanceolata",
    family: "Plantaginaceae",
    layer: "groundcover",
    edible: true,
    functions: ["forage", "medicine", "dynamic-accumulator"],
    hz: [3, 9],
    years: 1,
    companions: ["sheep", "clover-white"],
    fodderFor: ["sheep", "chicken"],
    nutrients: { vitaminA: 30, calcium: 25 },
    description: "A pasture herb that livestock seek out. Anti-inflammatory, mineral-rich, drought hardy.",
    agro: "Include in every silvopasture seed mix. Indicator of compacted soil if it dominates.",
    yields: "Forage, leaf poultice",
    color: "sage",
    silhouette: "ground",
  }),
  s({
    id: "daffodil",
    name: "Daffodil",
    latin: "Narcissus pseudonarcissus",
    family: "Amaryllidaceae",
    layer: "herb",
    edible: false,
    functions: ["pest-deterrent"],
    hz: [3, 8],
    years: 1,
    companions: ["apple", "pear", "cherry"],
    livestockSafe: false,
    description: "Toxic to voles and rodents. A living trunk guard that happens to be beautiful.",
    agro: "Ring every young fruit tree. Livestock generally leave them. Do not feed the foliage.",
    yields: "Flowers, rodent deterrence",
    color: "mustard",
    silhouette: "tuft",
  }),
  s({
    id: "rhubarb",
    name: "Rhubarb",
    latin: "Rheum rhabarbarum",
    family: "Polygonaceae",
    layer: "herb",
    functions: ["food"],
    hz: [3, 7],
    years: 2,
    companions: ["comfrey"],
    nutrients: { vitaminK: 40, vitaminC: 20, calcium: 20, fiber: 25 },
    description: "Spring acid fruit that is actually a petiole. Leaves are toxic.",
    agro: "Edge of the kitchen garden or a damp orchard corner. A 15-year plant.",
    yields: "Stalks",
    color: "coral",
    silhouette: "herb",
  }),
  s({
    id: "horseradish",
    name: "Horseradish",
    latin: "Armoracia rusticana",
    family: "Brassicaceae",
    layer: "root",
    functions: ["food", "medicine", "pest-deterrent"],
    hz: [3, 8],
    years: 1,
    companions: ["potato"],
    nutrients: { vitaminC: 50 },
    description: "Contain it. One of the great condiments and a stubborn perennial.",
    agro: "A dedicated corner. Any fragment of root is a new plant.",
    yields: "Root",
    color: "sage",
    silhouette: "tuft",
  }),
  s({
    id: "fennel",
    name: "Bronze fennel",
    latin: "Foeniculum vulgare",
    family: "Apiaceae",
    layer: "herb",
    functions: ["food", "pollinator"],
    hz: [5, 9],
    water: "dry",
    years: 1,
    companions: [],
    antagonists: ["tomato", "bean-runner"],
    nutrients: { vitaminC: 20, potassium: 20 },
    description: "Swallowtail host and a licorice-scented insectary. Allelopathic to some vegetables.",
    agro: "Keep it in the pollinator strip, not the tomato alley.",
    yields: "Fronds, pollen, seed",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "calendula",
    name: "Calendula",
    latin: "Calendula officinalis",
    family: "Asteraceae",
    layer: "herb",
    functions: ["medicine", "pollinator", "food"],
    hz: [2, 11],
    years: 0,
    companions: ["tomato"],
    nutrients: { carotenoids: 40 },
    description: "Pot marigold. Petals in the salad, resin in the salve, hoverflies in the alley.",
    agro: "Self-sowing insectary. Deadhead if you do not want a carpet.",
    yields: "Petals",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "vetch",
    name: "Hairy vetch",
    latin: "Vicia villosa",
    family: "Fabaceae",
    layer: "vine",
    edible: false,
    functions: ["nitrogen-fixer", "soil-builder", "forage"],
    hz: [3, 8],
    years: 0,
    companions: ["rye"],
    fodderFor: ["sheep", "cattle"],
    description: "The winter nitrogen engine. A vetch-rye mix is the standard cover for temperate alleys.",
    agro: "Sow in fall with rye. Terminate in spring before seed. Can tangle a small tree if you ignore it.",
    yields: "Nitrogen, mulch",
    color: "vine",
    silhouette: "vine",
  }),
  s({
    id: "lupin",
    name: "Blue lupine",
    latin: "Lupinus perennis",
    family: "Fabaceae",
    layer: "herb",
    edible: false,
    functions: ["nitrogen-fixer", "pollinator"],
    hz: [3, 8],
    soils: ["sand", "loam"],
    water: "dry",
    years: 2,
    companions: ["pine"],
    description: "Native nitrogen fixer and the host plant of the Karner blue. Beautiful, not a forage.",
    agro: "Sandy, acidic edges and pine understory. Do not confuse with bitter agricultural lupines.",
    yields: "Nitrogen, habitat",
    color: "vine",
    silhouette: "herb",
  }),
  s({
    id: "lupin-white",
    name: "White lupin",
    latin: "Lupinus albus",
    family: "Fabaceae",
    layer: "herb",
    functions: ["nitrogen-fixer", "soil-builder", "food"],
    hz: [5, 9],
    soils: ["sand", "loam", "silt"],
    water: "moderate",
    root: "deep",
    years: 0,
    companions: ["wheat", "apple", "clover-white"],
    nutrients: { protein: 55, fiber: 40, folate: 35, iron: 30, magnesium: 30 },
    description: "The cluster-root P pump. Under phosphorus stress it dumps citrate and malate and exports genistein — a documented, not folkloric, nutrient service.",
    agro: "Use on P-fixing clays and acid sands before or beside a hungry alley crop. Sweet (low-alkaloid) cultivars only if you intend to eat the seed. Not the native blue lupine.",
    yields: "Seed, phosphate, nitrogen",
    color: "vine",
    silhouette: "herb",
  }),
  s({
    id: "faba",
    name: "Faba bean",
    latin: "Vicia faba",
    family: "Fabaceae",
    layer: "herb",
    functions: ["nitrogen-fixer", "food", "soil-builder"],
    hz: [3, 8],
    years: 0,
    companions: ["corn", "wheat", "apple"],
    nutrients: { protein: 50, folate: 55, iron: 35, fiber: 40, magnesium: 30 },
    description: "The cereal's best-studied intercrop. Mixed stands exude more nod-inducing flavonoids than faba grown alone.",
    agro: "Pair with maize or a young tree alley. Organic acids lift labile P for the neighbor; N moves by rhizodeposition and, where present, a common mycelial network.",
    yields: "Beans, nitrogen, phosphate",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "alfalfa",
    name: "Alfalfa",
    latin: "Medicago sativa",
    family: "Fabaceae",
    layer: "herb",
    functions: ["nitrogen-fixer", "forage", "soil-builder"],
    hz: [4, 8],
    root: "deep",
    years: 1,
    companions: ["sheep", "cattle", "honey-locust"],
    fodderFor: ["sheep", "cattle", "rabbit"],
    nutrients: { protein: 40, calcium: 30, vitaminK: 25 },
    description: "Deep-rooted lucerne. Luteolin and daidzein drive nodulation; saponins in the litter slow decomposition slightly.",
    agro: "Silvopasture understory under a high canopy. Manage bloat on pure stands. A multi-year N and mineral pump.",
    yields: "Hay, nitrogen",
    color: "sage",
    silhouette: "herb",
  }),
  s({
    id: "sorghum",
    name: "Sorghum",
    latin: "Sorghum bicolor",
    family: "Poaceae",
    layer: "herb",
    functions: ["food", "fodder"],
    hz: [6, 10],
    water: "dry",
    years: 0,
    companions: [],
    antagonists: ["tomato"],
    allelopathic: true,
    fodderFor: ["cattle", "chicken"],
    nutrients: { protein: 20, fiber: 25, magnesium: 20 },
    description: "Sorgoleone from root hairs is one of the best-documented weed-suppressing exudates in agriculture.",
    agro: "Managed alley cover or dryland grain. Hydrophobic allelochemical persists in SOM — do not sow sensitive seedlings into fresh sorghum residue.",
    yields: "Grain, forage, weed suppression",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "mustard",
    name: "Brown mustard",
    latin: "Brassica juncea",
    family: "Brassicaceae",
    layer: "herb",
    functions: ["food", "pest-deterrent", "soil-builder"],
    hz: [3, 9],
    years: 0,
    companions: [],
    antagonists: ["hazel", "truffle", "apple", "clover-white"],
    nutrients: { vitaminC: 40, vitaminK: 20 },
    description: "Glucosinolates hydrolyze to isothiocyanates — a biofumigant. Hostile to AMF, so it is a rotation tool, not a permanent understory.",
    agro: "Chop and incorporate before a disease-prone alley. Leave a season before replanting hazel, truffle hosts, or apple.",
    yields: "Greens, seed, biofumigation",
    color: "mustard",
    silhouette: "herb",
  }),
  s({
    id: "dandelion",
    name: "Dandelion",
    latin: "Taraxacum officinale",
    family: "Asteraceae",
    layer: "herb",
    functions: ["food", "dynamic-accumulator", "medicine"],
    hz: [3, 9],
    years: 1,
    companions: ["apple", "clover-white", "sheep"],
    fodderFor: ["chicken", "rabbit"],
    nutrients: { vitaminA: 55, vitaminK: 60, vitaminC: 30, iron: 30, calcium: 25, potassium: 30 },
    description: "Ca, K, Fe, Mg miner with a taproot that opens compaction. Organic acids (malate, oxalate) work locally.",
    agro: "Leave it in the sward. Harvest greens and roots. A weed only if you wanted a putting green.",
    yields: "Greens, root, minerals",
    color: "mustard",
    silhouette: "tuft",
  }),
  s({
    id: "leucaena",
    name: "Leucaena",
    latin: "Leucaena leucocephala",
    family: "Fabaceae",
    layer: "canopy",
    functions: ["nitrogen-fixer", "fodder", "coppice", "timber"],
    hz: [9, 12],
    soils: ["loam", "sand", "rocky", "clay"],
    water: "dry",
    root: "deep",
    years: 2,
    companions: ["eucalyptus", "mesquite"],
    antagonists: ["tomato", "bean-runner"],
    allelopathic: true,
    livestockSafe: false,
    fodderFor: ["goat", "cattle"],
    nutrients: { protein: 45, calcium: 25 },
    description: "Tropical N-fixer that also makes mimosine — a toxic amino-acid analog. Useful coppice fodder only with adapted ruminants.",
    agro: "Hot-zone alley or silvopasture nurse. Mimosine inhibits many understories and unadapted livestock. Goats and cattle that carry Synergistes jonesii can detoxify it; everyone else cannot. Do not treat it as a friendly clover.",
    yields: "Fodder, poles, nitrogen",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "eucalyptus",
    name: "River red gum",
    latin: "Eucalyptus camaldulensis",
    family: "Myrtaceae",
    layer: "canopy",
    edible: false,
    functions: ["timber", "windbreak", "medicine"],
    hz: [8, 11],
    soils: ["loam", "sand", "clay", "silt"],
    water: "dry",
    root: "deep",
    years: 4,
    companions: ["leucaena", "mesquite"],
    antagonists: ["tomato", "clover-white", "apple"],
    allelopathic: true,
    livestockSafe: true,
    description: "1,8-cineole and phenolic litter rewrite the soil under a pure stand. A timber and windbreak tree, not a vegetable nurse.",
    agro: "Pair with an N-fixer (leucaena, mesquite) if you must mix. Do not underplant a tomato or clover alley. Litter is hydrophobic and slow; keep it on the dry windward edge.",
    yields: "Timber, oil, windbreak",
    color: "sage",
    silhouette: "canopy",
  }),
  s({
    id: "shiitake",
    name: "Shiitake",
    latin: "Lentinula edodes",
    family: "Omphalotaceae",
    kind: "fungi",
    layer: "fungi",
    functions: ["food", "medicine"],
    hz: [4, 8],
    sun: "shade",
    water: "wet",
    years: 1,
    companions: ["oak-white"],
    nutrients: { vitaminD: 70, protein: 30, copper: 45, selenium: 35, zinc: 25, b6: 20, fiber: 30 },
    description: "The farm mushroom. Inoculated oak bolts fruit for years in the shade of the very trees they came from.",
    agro: "A shiitake yard in the north shade of the oak or chestnut block. Stack bolts, keep them damp, force with a soak when you want a flush.",
    yields: "Mushrooms",
    color: "bark",
    silhouette: "fungi",
  }),
  s({
    id: "winecap",
    name: "Wine cap",
    latin: "Stropharia rugosoannulata",
    family: "Strophariaceae",
    kind: "fungi",
    layer: "fungi",
    functions: ["food", "soil-builder"],
    hz: [4, 8],
    sun: "shade",
    years: 0,
    companions: ["hazel", "apple"],
    nutrients: { protein: 25, fiber: 25, copper: 30 },
    description: "Garden giant. Runs through wood-chip mulch under shrubs and fruit trees.",
    agro: "Inoculate fresh chip mulch in the hazel or apple understory. A soil-food-web booster that also makes dinner.",
    yields: "Mushrooms, soil life",
    color: "coral",
    silhouette: "fungi",
  }),
  s({
    id: "truffle",
    name: "Périgord truffle",
    latin: "Tuber melanosporum",
    family: "Tuberaceae",
    kind: "fungi",
    layer: "fungi",
    functions: ["food"],
    hz: [6, 9],
    soils: ["loam", "rocky"],
    sun: "part",
    years: 8,
    companions: ["hazel", "oak-white"],
    nutrients: { protein: 20 },
    description: "The luxury mycorrhizal crop. Needs the right host, high pH, and patience.",
    agro: "Inoculated hazel or oak on well-drained calcareous ground. Keep the brulé clean. A trained dog is the harvest tool.",
    yields: "Truffles",
    color: "ink",
    silhouette: "fungi",
  }),
  s({
    id: "morel",
    name: "Morel",
    latin: "Morchella americana",
    family: "Morchellaceae",
    kind: "fungi",
    layer: "fungi",
    functions: ["food"],
    hz: [3, 8],
    sun: "part",
    years: 3,
    companions: ["oak-white", "maple", "apple"],
    nutrients: { vitaminD: 50, iron: 40, copper: 35 },
    description: "Not reliably farmed, but orchard and oak edges fruit after wet springs. Treat as a gift, not a line item.",
    agro: "Leave woody debris, do not till the oak-maple edge, and walk the orchard in April.",
    yields: "Mushrooms (unpredictable)",
    color: "bark",
    silhouette: "fungi",
  }),

  // ── livestock ──────────────────────────────────────────
  s({
    id: "chicken",
    name: "Chicken",
    latin: "Gallus gallus domesticus",
    family: "Phasianidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "pest-deterrent", "protein"],
    hz: [3, 10],
    soils: ["loam", "sand", "silt", "clay"],
    water: "moderate",
    sun: "part",
    years: 0,
    companions: ["apple", "mulberry", "chestnut", "comfrey", "grape", "clover-white"],
    antagonists: [],
    fodderFor: [],
    nutrients: { protein: 70, b12: 80, vitaminD: 30, selenium: 40, riboflavin: 45, iron: 25 },
    description: "The orchard sanitation crew. They eat dropped fruit, larvae, ticks, and leftover grain, and they leave nitrogen exactly where the drip line wants it.",
    agro: "Classic silvopasture: rotate a flock under apples and mulberries. Trees give shade and hawk cover; birds cut pest pressure and feed bills. Keep them off young bark and off beds you still need intact.",
    yields: "Eggs, meat, pest control, manure",
    color: "mustard",
    silhouette: "chicken",
  }),
  s({
    id: "duck",
    name: "Duck",
    latin: "Anas platyrhynchos domesticus",
    family: "Anatidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "pest-deterrent", "protein"],
    hz: [3, 10],
    water: "wet",
    years: 0,
    companions: ["willow", "elderberry", "rice", "slug-beds"],
    nutrients: { protein: 65, b12: 75, iron: 35, selenium: 35, omega3: 30 },
    description: "Slug specialists. Happier in wet, shady systems than chickens, and their eggs are a farmstead luxury.",
    agro: "Riparian food forest and wet alleys. They do not scratch beds to pieces the way chickens do. Need water to dunk their heads.",
    yields: "Eggs, meat, slug control",
    color: "ink",
    silhouette: "duck",
  }),
  s({
    id: "goose",
    name: "Goose",
    latin: "Anser anser domesticus",
    family: "Anatidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "forage", "protein"],
    hz: [3, 9],
    years: 0,
    companions: ["apple", "chestnut"],
    nutrients: { protein: 60, b12: 70 },
    description: "Living mower. They prefer grass to most crops, which makes them orchard weeding tools.",
    agro: "Graze mature orchards. They will eat fruit within reach and can be aggressive in nesting season — plan fencing.",
    yields: "Meat, down, weeding",
    color: "ink",
    silhouette: "duck",
  }),
  s({
    id: "turkey",
    name: "Turkey",
    latin: "Meleagris gallopavo",
    family: "Phasianidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "pest-deterrent", "protein"],
    hz: [4, 9],
    years: 0,
    companions: ["oak-white", "chestnut"],
    nutrients: { protein: 75, selenium: 50, b12: 70, niacin: 55, b6: 40 },
    description: "Mast-finishing bird. They range farther than chickens and eat a shocking number of ticks.",
    agro: "Wooded pasture in autumn. Need high roosts and serious predator cover.",
    yields: "Meat, tick control",
    color: "bark",
    silhouette: "chicken",
  }),
  s({
    id: "guinea",
    name: "Guinea fowl",
    latin: "Numida meleagris",
    family: "Numididae",
    kind: "animal",
    layer: "animal",
    functions: ["pest-deterrent", "food"],
    hz: [6, 10],
    years: 0,
    companions: ["apple"],
    nutrients: { protein: 60 },
    description: "Tick and wasp patrol with an alarm-call that announces every hawk and visitor.",
    agro: "Free-range around the orchard if you can stand the noise. They fly, so they are not a fence-in bird.",
    yields: "Pest control, meat",
    color: "ink",
    silhouette: "chicken",
  }),
  s({
    id: "sheep",
    name: "Sheep",
    latin: "Ovis aries",
    family: "Bovidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "forage", "protein"],
    hz: [3, 9],
    years: 0,
    companions: ["honey-locust", "oak-white", "chestnut", "clover-white", "chicory", "willow"],
    nutrients: { protein: 70, b12: 80, zinc: 45, iron: 30, selenium: 30 },
    description: "The silvopasture grazer of choice on smaller acreage. Hair sheep skip the shearing. They browse higher than cattle think to.",
    agro: "Under high-pruned trees. In Florida heat, use hair sheep (Katahdin, Gulf Coast Native) — wool breeds suffer. Protect trunks until bark is thick. Chicory and plantain in the sward keep parasites down. Rotate off wet flatwoods in the rainy season.",
    yields: "Meat, milk, fiber, fertility",
    color: "bark",
    silhouette: "sheep",
  }),
  s({
    id: "goat",
    name: "Goat",
    latin: "Capra hircus",
    family: "Bovidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "forage", "protein"],
    hz: [5, 10],
    years: 0,
    companions: ["willow", "black-locust", "mulberry"],
    antagonists: ["apple"],
    nutrients: { protein: 65, b12: 70, calcium: 25 },
    description: "Browsers, not grazers. They will eat your fruit trees if you let them. They will also clear a multiflora rose thicket you could not.",
    agro: "Use on rough, brushy ground and coppice stools (willow, locust), not in a young orchard. Fences must be better than you think.",
    yields: "Milk, meat, brush control",
    color: "bark",
    silhouette: "goat",
  }),
  s({
    id: "cattle",
    name: "Cattle",
    latin: "Bos taurus",
    family: "Bovidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "forage", "protein"],
    hz: [3, 11],
    years: 0,
    companions: ["honey-locust", "oak-white", "oak-live", "mesquite", "switchgrass", "clover-white"],
    nutrients: { protein: 70, b12: 90, zinc: 50, iron: 35, omega3: 15 },
    description: "Need shade, need grass, leave fertility. The reason silvopasture exists as a named practice.",
    agro: "Wide-spaced high canopy over a diverse sward. Shade cuts heat stress and raises gains. In Florida use heat-adapted cattle (Brahman influence) and rest paddocks off ponded sand. Never overstock a young tree.",
    yields: "Beef, dairy, fertility",
    color: "ink",
    silhouette: "cow",
  }),
  s({
    id: "pig",
    name: "Pig",
    latin: "Sus scrofa domesticus",
    family: "Suidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "protein"],
    hz: [4, 9],
    years: 0,
    companions: ["oak-white", "chestnut", "hazel", "mulberry", "sunchoke"],
    antagonists: ["apple"],
    nutrients: { protein: 65, thiamin: 60, selenium: 40, zinc: 35, b12: 55 },
    description: "Mast finishers and living rototillers. In the right season they harvest acorns and chestnuts you would have lost to weevils.",
    agro: "Flash-graze mast years in oak/chestnut stands. Use them to convert a sunchoke patch into pork. They will ring-bark trees and wreck roots if left too long — short, watched pulses.",
    yields: "Meat, tillage",
    color: "coral",
    silhouette: "pig",
  }),
  s({
    id: "rabbit",
    name: "Rabbit",
    latin: "Oryctolagus cuniculus",
    family: "Leporidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure", "protein"],
    hz: [3, 10],
    years: 0,
    companions: ["comfrey", "willow", "clover-white"],
    nutrients: { protein: 75, b12: 60 },
    description: "The small-farm protein engine. Manure is cold enough to go straight on beds.",
    agro: "Colony under a shade roof, or tractor on clover. Feed comfrey, willow, and garden waste. Keep them out of the bark of young trees.",
    yields: "Meat, manure",
    color: "bark",
    silhouette: "rabbit",
  }),
  s({
    id: "bee",
    name: "Honeybee",
    latin: "Apis mellifera",
    family: "Apidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "pollinator"],
    hz: [3, 10],
    years: 0,
    companions: ["apple", "chestnut", "lavender", "buckwheat", "clover-white", "black-locust"],
    nutrients: { polyphenols: 30 },
    description: "The farm's flying mutualism. Every rosaceous fruit tree is a customer.",
    agro: "Set hives on the warm edge of the orchard. Sequence bloom: willow, locust, apple, chestnut, buckwheat, goldenrod. Leave a water source.",
    yields: "Honey, wax, pollination",
    color: "mustard",
    silhouette: "bee",
  }),
  s({
    id: "alpaca",
    name: "Alpaca",
    latin: "Vicugna pacos",
    family: "Camelidae",
    kind: "animal",
    layer: "animal",
    functions: ["food", "manure"],
    hz: [4, 8],
    years: 0,
    companions: ["clover-white", "apple"],
    nutrients: { protein: 40 },
    description: "Light-footed grazer with a fiber crop. Soft pads, not hooves — gentler on tree roots than cattle.",
    agro: "Small-acreage orchard grazer. They do not browse as hard as goats. Fiber is the product; meat is secondary.",
    yields: "Fiber, guardian presence",
    color: "bark",
    silhouette: "sheep",
  }),
  ...FLORIDA_SPECIES,
];

// autumn-olive used a slightly loose functions cast — normalize any leftovers
for (const sp of SPECIES) {
  sp.functions = sp.functions.filter(Boolean);
  const extra = NUTRIENT_BOOSTS[sp.id];
  if (extra) Object.assign(sp.nutrients, extra);
}

export const SPECIES_BY_ID: Record<string, Species> = Object.fromEntries(
  SPECIES.map((sp) => [sp.id, sp]),
);

export function getSpecies(id: string): Species | undefined {
  return SPECIES_BY_ID[id];
}

export function searchSpecies(query: string): Species[] {
  const q = query.trim().toLowerCase();
  if (!q) return SPECIES;
  return SPECIES.filter((sp) => {
    const hay = [
      sp.name,
      sp.latin,
      sp.family,
      sp.layer,
      sp.kind,
      ...sp.functions,
      sp.description,
      sp.agro,
      sp.yields,
      chemistryHaystack(sp),
    ]
      .join(" ")
      .toLowerCase();
    return hay.includes(q);
  });
}

export const FAMILIES = [...new Set(SPECIES.map((s) => s.family))].sort();
